/hikrobot_camera:
  ros__parameters:
    use_sim_time: false
    serial_number: ""
    ip_address: ""
    image_topic: "image_raw"
    frame_id: "camera_optical_frame"
    exposure_time: 10000.0 
    gain: 0.0
    frame_rate: 0.0
    pixel_format: "YUV422_YUYV_Packed"
    reconnect_interval: 1.0
